### ISSUE TITLE
[Question]: Why did you removed `productName` from `WindowsDeviceInfo` ?

### ISSUE THREAD

**Issue by gehad-ahmed-mohammed** [fluttercommunity/plus_plugins#1023]
### What is your question?

You removed almost all `WindowsDeviceInfo` .. why did you do this ?

**Comment by alexmercerind** [comment]
Hey!

It was me who added all the necessary information for Windows in https://github.com/fluttercommunity/plus_plugins/pull/814 including the `productName`.

It got reverted because of not incrementing the versions semantically.

Some Flutter _engineers_ got confused by it at #1000.
Instead of actually trying to increment the version of `device_info_plus` in `pubspec.yaml` of their app, they tried editing package's internal code or forcing dependency overrides. I'm speechless. 

At the moment you have two choices:

1. Force pin `device_info_plus` version to `4.0.2` in your `pubspec.yaml` file.

```yaml
dependencies:
  device_info_plus: 4.0.2
```

3. Use package from my fork.

```yaml
dependencies:
  device_info_plus:
    git:
      url: https://github.com/alexmercerind/plus_plugins.git
      path: packages/device_info_plus/device_info_plus
      ref: main

dependency_overrides:
  device_info_plus_platform_interface:
    git:
      url: https://github.com/alexmercerind/device_info_plus.git
      path: packages/device_info_plus/device_info_plus_platform_interface
      ref: main
  device_info_plus_windows:
    git:
      url: https://github.com/alexmercerind/device_info_plus.git
      path: packages/device_info_plus/device_info_plus_windows
      ref: main
  device_info_plus_linux:
    git:
      url: https://github.com/alexmercerind/device_info_plus.git
      path: packages/device_info_plus/device_info_plus_linux
      ref: main
  device_info_plus_macos:
    git:
      url: https://github.com/alexmercerind/device_info_plus.git
      path: packages/device_info_plus/device_info_plus_macos
      ref: main
```
