### ISSUE TITLE
[Bug]: Xcode Cloud: module 'package_info_plus' not found

### ISSUE THREAD

**Issue by zdnk** [fluttercommunity/plus_plugins#1024]
### Platform

iOS 15

### Plugin

package_info_plus

### Version

1.4.3

### Flutter SDK

3.0.5

### Steps to reproduce

Not sure, maybe I am doing something wrong. I just have project with the package. I get:
> module 'package_info_plus' not found

### Code Sample

Pubspec
```
name: xxxx
description: A new Flutter project.
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fimber: ^0.6.6
  get_it: ^7.2.0
  sentry_flutter: ^6.5.1
  flutter_dotenv: ^5.0.2
  firebase_core: ^1.17.1
  stacked: ^2.3.12
  firebase_core_web: ^1.6.4
  package_info_plus_web: ^1.0.5
  package_info_plus: ^1.4.3
  gap: ^2.0.0
  flutter_staggered_grid_view: 0.4.0
  syncfusion_flutter_datepicker: ^20.2.38
  flutter_svg: ^1.1.1+1
  flutter_stripe: ^4.0.0
  sliding_up_panel: ^2.0.0+1
  persistent_bottom_nav_bar_v2: ^4.2.4
  firebase_auth: ^3.6.2
  graphql_flutter: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dependency_validator: ^3.2.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - .env
flutter_intl:
  enabled: true

```
post clone script:
```
#!/bin/sh

# The default execution directory of this script is the ci_scripts directory.
cd $CI_WORKSPACE # change working directory to the root of your cloned repo.

# Install Flutter using git.
git clone https://github.com/flutter/flutter.git --depth 1 -b stable $HOME/flutter
export PATH="$PATH:$HOME/flutter/bin"

# Install Flutter artifacts for iOS (--ios), or macOS (--macos) platforms.
flutter precache --ios

# Install Flutter dependencies.
flutter pub get

# Install CocoaPods using Homebrew.
HOMEBREW_NO_AUTO_UPDATE=1 # disable homebrew's automatic updates.
brew install cocoapods

# Install CocoaPods dependencies.
cd ios && pod install # run `pod install` in the `ios` directory.

exit 0
```

### Logs

```shell
/Volumes/workspace/repository/ios/Runner/GeneratedPluginRegistrant.m:30:9: fatal error: module 'package_info_plus' not found
@import package_info_plus;
 ~~~~~~~^~~~~~~~~~~~~~~~~
```

### Flutter Doctor

```shell
[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

[✓] Flutter (Channel unknown, 3.0.5, on macOS 12.5 21G72 darwin-x64, locale en)

    • Flutter version 3.0.5 at /Users/local/flutter

    • Upstream repository unknown

    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700

    • Engine revision e85ea0e79c

    • Dart version 2.17.6

    • DevTools version 2.12.2



[✗] Android toolchain - develop for Android devices

    ✗ Unable to locate Android SDK.

      Install Android Studio from: https://developer.android.com/studio/index.html

      On first launch it will assist you in installing the Android SDK components.

      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

      If the Android SDK has been installed to a custom location, please use

      `flutter config --android-sdk` to update to that location.





[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)

    • Xcode at /Applications/Xcode.app/Contents/Developer

    • CocoaPods version 1.11.3



[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)

    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.



[!] Android Studio (not installed)

    • Android Studio not found; download from https://developer.android.com/studio/index.html

      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).



[✓] Connected device (1 available)

    • macOS (desktop) • macos • darwin-x64 • macOS 12.5 21G72 darwin-x64



[✓] HTTP Host Availability

    • All required HTTP hosts are available



! Doctor found issues in 3 categories.
```
