### ISSUE TITLE
[Question]:  Getting issue after upgrading from 8.2.0 to 8.2.1

### ISSUE THREAD

**Issue by fbernaly** [fluttercommunity/plus_plugins#1724]
### What is your question?

I ran `flutter pub upgrade` and the only changes were this:

![Screenshot 2023-04-26 at 10 02 31 AM](https://user-images.githubusercontent.com/7014968/234649624-4184da23-a428-407b-810f-702153333538.png)

device_info_plus from 8.2.0 -> 8.2.1 and after that I cannot compile my app, if I discard those changes and go back to 8.2.0 it compiles, but not with 8.2.1. It throws this error:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/user/.pub-cache/hosted/pub.dartlang.org/device_info_plus-8.2.1/android/build.gradle' line: 27

* What went wrong:
A problem occurred evaluating project ':device_info_plus'.
> No signature of method: build_5njhyus0pkrfafzzws19dn4qr.android() is applicable for argument types: (build_5njhyus0pkrfafzzws19dn4qr$_run_closure2) values: [build_5njhyus0pkrfafzzws19dn4qr$_run_closure2@64c10c91]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1
```

I was reading in the CHANGELOG FOR device_info_plus and says this for 8.2.1:

![Screenshot 2023-04-26 at 10 05 42 AM](https://user-images.githubusercontent.com/7014968/234650236-589e7371-4491-473e-b0a6-6852dcee9f67.png)

But in my case it is breaking my app. I could not fin anything in the README, so, what should I add to my gradle to compile with 8.2.1?

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
It seems to be similar to #1722 

See https://github.com/fluttercommunity/plus_plugins/issues/1722#issuecomment-1523942526 for a solution

**Comment by nohli** [comment]
@fbernaly please try with this imports in pubspec.yaml if it fixes your problem:
(if it's for a different package than share_plus, you can edit the path)

```
  device_info_plus:
    git:
      url: https://github.com/fluttercommunity/plus_plugins.git
      path: packages/device_info_plus/device_info_plus
      ref: fix-agp-prior-7

  package_info_plus:
    git:
      url: https://github.com/fluttercommunity/plus_plugins.git
      path: packages/package_info_plus/package_info_plus
      ref: fix-agp-prior-7
```
