### ISSUE TITLE
[Request]: When to support Android V2

### ISSUE THREAD

**Issue by codepgq** [fluttercommunity/plus_plugins#1890]
### Plugin

Android V2

### Use case

`pubspec.lock`
```
...
  connectivity_plus:
    dependency: transitive
    description:
      name: connectivity_plus
      sha256: "8599ae9edca5ff96163fca3e36f8e481ea917d1e71cdad912c084b5579913f34"
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "4.0.1"
...
```

run `flutter pub get`

This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
The plugin `connectivity_plus` requires your app to be migrated to the Android embedding v2. Follow the steps on the migration doc above and re-run this command.

### Proposal

Do you have a plan?
