### ISSUE TITLE
[Request][sensors_plus]: make  `package` in pubspec.yaml the same with `group` in build.gradle

### ISSUE THREAD

**Issue by zhyky** [fluttercommunity/plus_plugins#2091]
### Plugin

sensors_plus

### Use case

Currently, `sensors_plus` plugin has different value between `package` in pubspec.yaml and `group` in build.gradle

in pubspec.yaml
```yaml
flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.sensors
        pluginClass: SensorsPlugin
```

in android/build.gradle
```gradle
group 'io.flutter.plugins.sensors'
version '1.0-SNAPSHOT'
```

This will lead to strange behavior when checking tools written in dart read the package in `pubspec.yaml`

### Proposal

Please make these two value same
