### ISSUE TITLE
Could not determine the dependencies of task ':package_info_plus:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by Mastersam07** [fluttercommunity/plus_plugins#3076]
### Operating System

MacOS Sonoma 14.5

### Plugin

device_info_plus

### Version

10.1.0

### Flutter SDK

3.22.2

### Compilation command

flutter run

### Dart Dependencies

```yaml
cached_network_image: ^3.2.3

  cupertino_icons: ^1.0.2
  device_info_plus: ^10.1.0
  dio: ^5.5.0+1
  dropdown_button2: ^2.3.9
  ficonsax: ^0.0.3
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  firebase_messaging: ^15.0.2
  flutter:
    sdk: flutter
  flutter_background_geolocation: ^4.10.3
  flutter_dotenv: ^5.0.2
  flutter_font_icons: ^2.2.5
  flutter_libphonenumber: ^2.2.2
  flutter_local_notifications: ^17.2.1
  flutter_polyline_points: ^1.0.0
  flutter_screenutil: ^5.3.1
  flutter_secure_storage: ^9.2.2
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.5
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get_it: ^7.2.0
  google_api_headers:

  #  location_permissions: ^4.0.1
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.3
  google_maps_webservice:
  google_place: ^0.4.7
  hive_flutter: ^1.1.0
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  internet_connection_checker:
  intl: ^0.18.0
  just_the_tooltip: ^0.0.12
  kt_dart: ^1.0.0
  loading_overlay: ^0.3.0
  local_auth: ^2.1.6
  local_auth_android: ^1.0.41
  local_auth_ios:
  logging: ^1.1.1
  lottie: ^3.0.0
  map_launcher: ^3.3.1
  mime: ^1.0.4
  package_info_plus: ^8.0.0
  path_provider: ^2.0.14
  pin_code_fields: ^8.0.1
  posthog_flutter:
    git:
      url: git@github.com:shuttlershq/posthog-flutter.git
      ref: main
  provider: ^6.0.2
  qr_flutter: ^4.1.0
  rxdart: ^0.27.5
  salesiq_mobilisten: ^6.1.0
  screenshot: ^3.0.0
  shared_preferences: ^2.0.17
  shimmer: ^3.0.0
  shuttlers_stories:
    git:
      url: git@github.com:shuttlershq/shuttlers-stories.git
      ref: 02a7c0d43ea10ffecdef8466691a57c6b60d1b04
  string_similarity: ^2.0.0
  swipeable_tile: ^2.0.0+3
  tuple: ^2.0.1
  url_launcher: ^6.1.8
```

### Compilation Error

```shell
[   +6 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Could not determine the dependencies of task ':package_info_plus:compileDebugJavaWithJavac'.
[        ] > Cannot query the value of this provider because it has no value available.
[        ] * Try:
[        ] > Run with --debug option to get more log output.
[        ] > Run with --scan to get full insights.
[        ] > Get more help at https://help.gradle.org.
[        ] * Exception is:
[        ] org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':package_info_plus:compileDebugJavaWithJavac'.
[        ] 	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:68)
[        ] 	at org.gradle.execution.plan.TaskDependencyResolver.resolveDependenciesFor(TaskDependencyResolver.java:49)
[        ] 	at org.gradle.execution.plan.LocalTaskNode.getDependencies(LocalTaskNode.java:148)
[        ] 	at org.gradle.execution.plan.LocalTaskNode.resolveDependencies(LocalTaskNode.java:122)
[        ] 	at org.gradle.execution.plan.DefaultExecutionPlan.discoverNodeRelationships(DefaultExecutionPlan.java:184)
[        ] 	at org.gradle.execution.plan.DefaultExecutionPlan.doAddEntryNodes(DefaultExecutionPlan.java:156)
[        ] 	at org.gradle.execution.plan.DefaultExecutionPlan.addEntryTasks(DefaultExecutionPlan.java:131)
[        ] 	at org.gradle.execution.plan.DefaultExecutionPlan.addEntryTasks(DefaultExecutionPlan.java:123)
[        ] 	at org.gradle.execution.TaskNameResolvingBuildTaskScheduler.scheduleRequestedTasks(TaskNameResolvingBuildTaskScheduler.java:54)
[        ] 	at org.gradle.execution.DefaultTasksBuildTaskScheduler.scheduleRequestedTasks(DefaultTasksBuildTaskScheduler.java:72)
[        ] 	at org.gradle.initialization.DefaultTaskExecutionPreparer.lambda$scheduleRequestedTasks$0(DefaultTaskExecutionPreparer.java:46)
[        ] 	at org.gradle.internal.Factories$1.create(Factories.java:31)
[        ] 	at org.gradle.internal.work.DefaultWorkerLeaseService.withReplacedLocks(DefaultWorkerLeaseService.java:360)
[        ] 	at org.gradle.api.internal.project.DefaultProjectStateRegistry$DefaultBuildProjectRegistry.withMutableStateOfAllProjects(DefaultProjectStateRegistry.java:239)
[        ] 	at org.gradle.api.internal.project.DefaultProjectStateRegistry$DefaultBuildProjectRegistry.withMutableStateOfAllProjects(DefaultProjectStateRegistry.java:232)
[        ] 	at org.gradle.initialization.DefaultTaskExecutionPreparer.scheduleRequestedTasks(DefaultTaskExecutionPreparer.java:45)
[        ] 	at org.gradle.initialization.VintageBuildModelController.lambda$scheduleRequestedTasks$0(VintageBuildModelController.java:76)
[        ] 	at org.gradle.internal.model.StateTransitionController.lambda$inState$1(StateTransitionController.java:99)
[        ] 	at org.gradle.internal.model.StateTransitionController.lambda$inState$2(StateTransitionController.java:114)
[        ] 	at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
[        ] 	at org.gradle.internal.model.StateTransitionController.inState(StateTransitionController.java:110)
[        ] 	at org.gradle.internal.model.StateTransitionController.inState(StateTransitionController.java:98)
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-NG)
    • Flutter version 3.22.2 on channel stable at /Users/codefarmer/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/codefarmer/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.91.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554             • android-arm64  • Android 15 (API 35) (emulator)
    • BatCell (mobile)                • 00008030-001874A911BB802E • ios            • iOS 17.3.1 21D61
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project
