### ISSUE TITLE
[Compile]: Im missing a signature file with error code ITMS-91065 when using share_plus

### ISSUE THREAD

**Issue by Frank-Ginger** [fluttercommunity/plus_plugins#3101]
### Operating System

iOS

### Plugin

share_plus

### Version

9.0.0

### Flutter SDK

3.19.6

### Compilation command

flutter build apk

### Dart Dependencies

```yaml
amplitude_flutter: 3.16.2
  appcheck: 1.1.0
  audio_video_progress_bar: 2.0.2
  carousel_slider: 4.2.1
  collection: 1.18.0
  connectivity: 3.0.6
  console: 4.1.0
  crypto: 3.0.3
  dart_openai: 5.1.0
  device_calendar: ^4.3.2
  device_info_plus: 10.1.0
  excel: 4.0.3
  file: 7.0.0
  file_saver: 0.2.13
  flutter:
    sdk: flutter
  flutter_cupertino_date_picker_fork: 1.0.7
  flutter_email_sender: 6.0.3
  flutter_keyboard_visibility: 6.0.0
  flutter_linkify: 6.0.0
  flutter_markdown: 0.7.1
  flutter_rating_bar: 4.0.1
  flutter_secure_storage: 9.0.0
  flutter_svg: 2.0.9
  flutter_pdfview: 1.3.2
  get_it: 7.7.0
  googleapis_auth: 1.6.0
  http: 1.2.1
  intl: 0.19.0
  intl_phone_field: 3.2.0
  intrinsic_dimension: 0.3.1
  jiffy: 6.3.1
  just_audio: 0.9.37
  jwt_decoder: 2.0.1
  libphonenumber_plugin: 0.3.3
  local_auth: 2.2.0
  local_auth_android: 1.0.38
  local_auth_darwin: 1.3.0
  logging: 1.2.0
  mask_text_input_formatter: 2.9.0
  meta: 1.12.0
  mutex: 3.1.0
  open_settings_plus: 0.3.3
  package_info_plus: 8.0.0
  path: 1.9.0
  path_provider: 2.1.3
  percent_indicator: 4.2.3
  provider: 6.1.2
  pull_to_refresh_flutter3: 2.0.2
  rxdart: 0.27.7
  shimmer: 3.0.0
  speech_to_text: 6.6.0
  sqflite_sqlcipher: 3.0.0
  timelines: 0.1.0
  timezone: 0.9.3
  universal_html: 2.2.4
  url_launcher: 6.2.6
  uuid: 4.4.0
  video_player: 2.8.6
  visibility_detector: 0.4.0+2
  wakelock_plus: 1.2.5
  webview_flutter: 4.8.0
  xml: any
```

### Compilation Error

```shell
ITMS-91065: Missing signature - Your app includes “Frameworks/connectivity_plus.framework/connectivity_plus”, which includes connectivity_plus, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. If a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a signature file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a signature. For details about verifying the code signature for a third-party SDK, visit: https://developer.apple.com/documentation/xcode/verifying-the-origin-of-your-xcframeworks.

ITMS-91065: Missing signature - Your app includes “Frameworks/share_plus.framework/share_plus”, which includes share_plus, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. If a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a signature file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a signature. For details about verifying the code signature for a third-party SDK, visit: https://developer.apple.com/documentation/xcode/verifying-the-origin-of-your-xcframeworks.
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.5 23F79 darwin-arm64, locale en-MX)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.90.2)
[✓] VS Code (version 1.77.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project
