### ISSUE TITLE
[Compile]: Packages incompatibility

### ISSUE THREAD

**Issue by erperejildo** [fluttercommunity/plus_plugins#3148]
### Operating System

Android

### Plugin

package_info_plus

### Version

1.4.3

### Flutter SDK

3.22.3

### Compilation command

flutter run

### Dart Dependencies

```yaml
  line_icons: ^2.0.3
  after_layout: ^1.2.0
  timezone: ^0.9.4
  maps_launcher: ^2.2.1 # REMOVED, USE OTHER INSTEAD
  uuid: ^4.4.2 # IDs for events
  cloudinary_public: ^0.23.1
  showcaseview: ^3.0.0 # help for new users
  provider: ^6.1.2
  cloud_firestore: ^5.2.0
  firebase_messaging: ^15.0.4
  firebase_core: ^3.3.0 # needs Runner/GoogleService-Info.plist
  firebase_auth: ^5.1.3 # needs Runner/GoogleService-Info.plist
  firebase_analytics: ^11.2.1 # needs Runner/GoogleService-Info.plist
  #  firebase_crashlytics: ^2.8.6 # needs Runner/GoogleService-Info.plist and NSAppTransportSecurity in Info.plist
  badges: ^3.1.2
  flutter_translate: ^4.1.0
  flutter_facebook_auth: ^4.3.3
  google_sign_in: ^6.2.1 # needs Info.plist modification
  sign_in_with_apple: ^6.1.1 # needs Xcode modification https://pub.dev/packages/sign_in_with_apple
  shared_preferences: ^2.3.1
  # intl: ^0.19.0 # locales for table_calendar and datetime manipulation
  jiffy: ^6.3.1 # date manipulation
  permission_handler: ^11.3.1 # needs Info.plist modification
  csv: ^6.0.0
  flutter_email_sender: ^6.0.3
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.1.2 # for camera
  image: ^4.2.0
  url_launcher: ^6.3.0 # needs Info.plist modification
  transparent_image: ^2.0.1
  carousel_slider: ^4.2.1
  flutter_slidable: ^3.1.1
  table_calendar: ^3.1.2
  add_2_calendar: ^3.0.1 # Info.plist modification
  in_app_purchase: ^3.2.0
  flutter_platform_widgets: ^7.0.1
  flutter_native_splash: ^2.4.1
  intl_phone_number_input: ^0.7.4
  country_pickers: ^3.0.1
  currency_picker: ^2.0.21
  #  country_currency_pickers: ^1.0.1
  reorderables: ^0.6.0 # reorder rent fields
  pdf: ^3.11.0
  printing: ^5.13.1 # necessary for the above one
  open_file_safe: ^3.2.3 # necessary for the above one
  #  flutter_statusbarcolor_ns: ^0.4.0 # DO NOT CHANGE
  fimber: ^0.7.0
  contacts_service: ^0.6.3 # get contacts. Info.plist modification
  http: ^0.13.6
  cached_network_image: ^3.3.0
  firebase_performance: ^0.10.0
  fluttercontactpicker: ^4.7.0
  flutter_local_notifications: ^12.0.4
  device_info_plus: ^4.0.0
  share_plus: ^4.5.3
  path_provider: ^2.0.8
  flutter_svg: ^1.1.6
  file_picker: ^4.6.1 # for multiple images selection
  package_info_plus: ^1.4.3
```

### Compilation Error

```shell
Resolving dependencies...
Because no versions of open_file_safe match >3.2.3 <4.0.0 and open_file_safe 3.2.3 depends on ffi ^1.0.0, open_file_safe ^3.2.3 requires ffi ^1.0.0.
And because package_info_plus ^1.4.3 depends on package_info_plus_windows ^2.0.0 which depends on ffi ^2.0.1, open_file_safe ^3.2.3 is incompatible with package_info_plus ^1.4.3.
So, because my_rents depends on both open_file_safe ^3.2.3 and package_info_plus ^1.4.3, version solving failed.
```

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22631.3958], locale en-GB)
    • Flutter version 3.22.3 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (3 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Dani\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\Dani\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34714.143
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[√] VS Code (version 1.92.0)
    • VS Code at C:\Users\Dani\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.94.0

[√] Connected device (4 available)
    • M2101K6G (mobile) • 996046da • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.22631.3958]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 127.0.6533.89
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 127.0.2651.86

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project
