### ISSUE TITLE
[Compile]: Error after upgrade dependencies version

### ISSUE THREAD

**Issue by ibrahimkelly** [fluttercommunity/plus_plugins#3176]
### Operating System

Windows 10

### Plugin

Share plus

### Version

^10.0.0

### Flutter SDK

3.22.3

### Compilation command

flutter run

### Dart Dependencies

```yaml
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  go_router: ^14.0.2
  font_awesome_flutter: ^10.6.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  http: ^1.1.2
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  country_code_picker: ^3.0.0
  flutter_native_splash: ^2.3.9
  carousel_slider: ^5.0.0
  loading_animation_widget: ^1.2.0+4
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  firebase_storage: ^12.0.1
  firebase_app_check: ^0.3.0+3
  intl_phone_field: ^3.2.0
  chips_choice: ^3.0.1
  textfield_tags: ^3.0.1
  cloud_firestore: ^5.0.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  source_gen: ^1.5.0
  path_provider: ^2.1.2
  flash: ^3.1.0
  flex_color_picker: ^3.4.1
  flutter_spinbox: ^0.13.1
  firebase_database: ^11.0.1
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.0.0
  skeletonizer: ^1.1.1
  flutter_staggered_animations: ^1.1.1
  sqflite: ^2.3.2
  flutter_gemini: ^2.0.3
  flutter_slidable: ^3.1.0
  pull_to_refresh_flutter3: ^2.0.2
  contacts_service: ^0.6.3
  swipe_to: ^1.0.6
  visibility_detector: ^0.4.0+2
  sticky_grouped_list: ^3.1.0
  draggable_home: ^1.0.5
  gap: ^3.0.1
  permission_handler: ^11.3.1
  workmanager: ^0.5.2
  flutter_carousel_widget: ^2.3.0
  photo_view: ^0.15.0
  share_plus: ^10.0.0
```

### Compilation Error

```shell
GeneratedPluginRegistrant.java:94: error: cannot find symbol       flutterEngine.getPlugins().add(new dev.fluttercommunity.plus.share.SharePlusPlugin());                                                                  ^   symbol:   class SharePlusPlugin   location: package dev.fluttercommunity.plus.share 1 error
```
```


### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.19045.4717], locale en-GB)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Chrome - develop for the web
[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2024.1)
[✓] VS Code (version 1.92.1)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category
```
```


### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project
