### ISSUE TITLE
[Compile]: I am facing an issue after updating Android Studio and flutter plugin updating.

### ISSUE THREAD

**Issue by ahsanrahman0745** [fluttercommunity/plus_plugins#3314]
### Operating System

mac 

### Plugin

device_info_plus: 

### Version

11.0.0

### Flutter SDK

Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git Framework • revision 2663184aa7 (4 weeks ago) • 2024-09-11 16:27:48 -0500 Engine • revision 36335019a8 Tools • Dart 3.5.3 • DevTools 2.37.3

### Compilation command

I am facing an issue after updating Android Studio and flutter plugin updating. when I run my app on android studio this give me this error.

Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':device_info_plus:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':device_info_plus:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /Users/ahsanrahman/Library/Android/sdk/platforms/android-34/core-for-system-modules.jar.
         > Error while executing process /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/jlink with arguments {--module-path /Users/ahsanrahman/.gradle/caches/transforms-3/21c78dd8912f2902e46be6383b37e2cc/transformed/output/temp/jmod --add-modules java.base --output /Users/ahsanrahman/.gradle/caches/transforms-3/21c78dd8912f2902e46be6383b37e2cc/transformed/output/jdkImage --disable-plugin system-modules}

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 28s
Error: Gradle task assembleDebug failed with exit code 1

### Dart Dependencies

```yaml
cupertino_icons: ^1.0.8
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  im_stepper: ^1.0.1+1
  http: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl_phone_field: ^3.2.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_crashlytics: ^4.1.3
  oktoast: ^3.4.0
  persistent_bottom_nav_bar: ^5.0.2
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  fluttericon: ^2.0.0
  hexcolor: ^3.0.1
  avatar_view: ^1.0.1
  flutter_staggered_grid_view: ^0.7.0
  appinio_video_player: ^1.2.2
  video_player: ^2.9.1
  audio_video_progress_bar: ^2.0.3
  audioplayers: ^5.2.1
  flutter_rating_bar: ^4.0.1
  flutter_speed_dial: ^7.0.0
  file_picker: ^8.1.2
  image_editor: ^1.5.1
  path_provider: ^2.1.4
  image_cropper: ^8.0.2
  image: ^4.2.0
  amazon_cognito_identity_dart_2: ^3.6.5
  permission_handler: ^11.3.1
  video_thumbnail: ^0.5.3
  flutter_image_compress: ^2.3.0
  flutter_launcher_icons: ^0.14.1
  refresh_loadmore: ^2.0.7
  gradient_borders: ^1.0.1
  url_launcher: ^6.3.1
  intl: ^0.19.0
  bottom_picker: ^2.8.0
  webview_flutter: ^4.9.0
  country_picker: ^2.0.26
  another_stepper: ^1.2.2
  rich_readmore: ^1.1.1
  simple_gradient_text: ^1.3.0
  share_plus: ^10.0.3
  bottom_sheet_scaffold: ^0.1.9
  shimmer: ^3.0.0
  device_info_plus: ^11.0.0
  ffmpeg_kit_flutter: ^6.0.3
#  video_compress: ^3.1.2
  readmore: ^3.0.0
  google_fonts: ^6.2.1
  keyboard_actions: ^4.2.0
  flutter_staggered_animations: ^1.1.1
  slide_countdown: ^2.0.0
  package_info_plus: ^8.0.2
  path: ^1.9.0
  flutter_swiper_view: ^1.1.8
  auto_size_text: ^3.0.0
  loading_animation_widget: ^1.3.0
  app_links: ^6.3.2
  network_info_plus: ^6.0.1
  flutter_widget_from_html: ^0.15.2
  percent_indicator: ^4.2.3
  flutter_spinkit: ^5.2.1
  widget_zoom: ^0.0.4
  photo_view: ^0.15.0
  timezone: ^0.9.4
```

### Native dependencies

```text
cupertino_icons: ^1.0.8
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  im_stepper: ^1.0.1+1
  http: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl_phone_field: ^3.2.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_crashlytics: ^4.1.3
  oktoast: ^3.4.0
  persistent_bottom_nav_bar: ^5.0.2
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  fluttericon: ^2.0.0
  hexcolor: ^3.0.1
  avatar_view: ^1.0.1
  flutter_staggered_grid_view: ^0.7.0
  appinio_video_player: ^1.2.2
  video_player: ^2.9.1
  audio_video_progress_bar: ^2.0.3
  audioplayers: ^5.2.1
  flutter_rating_bar: ^4.0.1
  flutter_speed_dial: ^7.0.0
  file_picker: ^8.1.2
  image_editor: ^1.5.1
  path_provider: ^2.1.4
  image_cropper: ^8.0.2
  image: ^4.2.0
  amazon_cognito_identity_dart_2: ^3.6.5
  permission_handler: ^11.3.1
  video_thumbnail: ^0.5.3
  flutter_image_compress: ^2.3.0
  flutter_launcher_icons: ^0.14.1
  refresh_loadmore: ^2.0.7
  gradient_borders: ^1.0.1
  url_launcher: ^6.3.1
  intl: ^0.19.0
  bottom_picker: ^2.8.0
  webview_flutter: ^4.9.0
  country_picker: ^2.0.26
  another_stepper: ^1.2.2
  rich_readmore: ^1.1.1
  simple_gradient_text: ^1.3.0
  share_plus: ^10.0.3
  bottom_sheet_scaffold: ^0.1.9
  shimmer: ^3.0.0
  device_info_plus: ^11.0.0
  ffmpeg_kit_flutter: ^6.0.3
#  video_compress: ^3.1.2
  readmore: ^3.0.0
  google_fonts: ^6.2.1
  keyboard_actions: ^4.2.0
  flutter_staggered_animations: ^1.1.1
  slide_countdown: ^2.0.0
  package_info_plus: ^8.0.2
  path: ^1.9.0
  flutter_swiper_view: ^1.1.8
  auto_size_text: ^3.0.0
  loading_animation_widget: ^1.3.0
  app_links: ^6.3.2
  network_info_plus: ^6.0.1
  flutter_widget_from_html: ^0.15.2
  percent_indicator: ^4.2.3
  flutter_spinkit: ^5.2.1
  widget_zoom: ^0.0.4
  photo_view: ^0.15.0
  timezone: ^0.9.4
```

### Compilation Error

```shell
Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':device_info_plus:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':device_info_plus:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /Users/ahsanrahman/Library/Android/sdk/platforms/android-34/core-for-system-modules.jar.
         > Error while executing process /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/jlink with arguments {--module-path /Users/ahsanrahman/.gradle/caches/transforms-3/21c78dd8912f2902e46be6383b37e2cc/transformed/output/temp/jmod --add-modules java.base --output /Users/ahsanrahman/.gradle/caches/transforms-3/21c78dd8912f2902e46be6383b37e2cc/transformed/output/jdkImage --disable-plugin system-modules}

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 28s
Error: Gradle task assembleDebug failed with exit code 1
```

### Flutter Doctor

```shell
Flutter (Channel stable, 3.24.3, on macOS 12.7.6 21H1320 darwin-x64, locale en-GB)
    • Flutter version 3.24.3 on channel stable at /Users/ahsanrahman/develpment/flutter_sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (4 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ahsanrahman/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    ! Flutter recommends a minimum Xcode version of 15.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)

[✓] VS Code (version unknown)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
    ✗ Unable to determine VS Code version.

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 12.7.6 21H1320 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 129.0.6668.100

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project
