### ISSUE TITLE
[Compile]: Framework Reachability not found

### ISSUE THREAD

**Issue by Foxsterc** [fluttercommunity/plus_plugins#3318]
### Operating System

Mac Sonoma

### Plugin

connectivity_plus

### Version

6.0.5

### Flutter SDK

3.24.3

### Compilation command

flutter build ipa --no-tree-shake-icons -- release

### Dart Dependencies

```yaml
intl: ^0.19.0
  get_it: ^8.0.0
  connectivity_plus: ^6.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  formz: ^0.7.0
  reactive_forms: ^17.0.1
  equatable: ^2.0.5
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  sign_in_with_apple: ^6.1.1
  syncfusion_flutter_charts: ^27.1.51
  syncfusion_flutter_core: ^27.1.51
  flutter_rating_bar: ^4.0.1
  gap: ^3.0.1
  go_router: ^14.2.1
  badges: ^3.1.2
  infinite_scroll_pagination: ^4.0.0
  map_launcher: ^3.3.1
  sprintf: ^7.0.0
  package_info_plus: ^8.0.0
  flutter_reactive_ble: ^5.3.1
  permission_handler: ^11.3.1
  mask_text_input_formatter: ^2.9.0
  drift: ^2.20.3
  beep_player: ^0.0.1
  collection: ^1.17.0
  url_launcher: ^6.3.0
  scrollable_positioned_list: ^0.3.8
  loader_overlay: ^4.0.2+1
  simple_animations: ^5.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  font_awesome_flutter: ^10.7.0
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  fast_cached_network_image: ^1.2.9
  firebase_app_check: ^0.3.1+3
  flutter_native_splash: ^2.4.1
```

### Compilation Error

```shell
Framework 'Reachability' not found

Linker command failed with exit code 1
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.3.1 23D60 darwin-arm64, locale en-GB)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] VS Code (version 1.94.2)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for Dale’s iPhone (2). Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project
