### ISSUE TITLE
[Compile]: 

### ISSUE THREAD

**Issue by MI-Soft** [fluttercommunity/plus_plugins#3328]
### Operating System

Windows 11

### Plugin

connectivity_plus

### Version

6.0.5

### Flutter SDK

3.22.2

### Compilation command

Execution failed for task ':connectivity_plus:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':connectivity_plus:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: C:\Users\dhili\AppData\Local\Android\sdk\platforms\android-34\core-for-system-modules.jar.
         > Error while executing process C:\Program Files\Android\Android Studio\jbr\bin\jlink.exe with arguments {--module-path C:\Users\dhili\.gradle\caches\transforms-3\72f109696607c2a2e011467aa233cdad\transformed\output\temp\jmod --add-modules java.base --output C:\Users\dhili\.gradle\caches\transforms-3\72f109696607c2a2e011467aa233cdad\transformed\output\jdkImage --disable-plugin system-modules}

### Dart Dependencies

```yaml
name: restart_tagxi
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  meta: ^1.12.0  
  google_fonts: ^4.0.4
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  pin_code_fields: ^8.0.1
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  page_transition: ^2.1.0
  share_plus: ^9.0.0
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
  audioplayers: ^6.0.0
  path_provider: ^2.1.4
  uuid: ^3.0.7

  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6  

  # Maps & Location
  google_maps_flutter: ^2.7.0
  geocoding: ^3.0.0
  flutter_map: ^7.0.1
  location: ^7.0.0
  geolocator: ^12.0.0
  latlong2: ^0.9.1
  flutter_google_places_sdk: ^0.3.7

  # localNotificaion
  flutter_local_notifications: ^17.2.1+1

  # Firebase
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_database: ^11.0.1
  firebase_messaging: ^15.0.1

  #shimmer
  shimmer: ^3.0.0

  #clipboard
  clipboard: ^0.1.3

  #contacts
  contacts_service: ^0.6.3

  #connectivity
  connectivity_plus: ^6.0.4

  # packageInfo
  package_info_plus: ^4.1.0

  # bottomsheet
  # modal_bottom_sheet: ^3.0.0

  # mapAnimation
  vector_math: ^2.1.4
  flutter_animarker: ^3.4.0-beta.1

  # draggable_bottom_sheet: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/audio/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

### Compilation Error

```shell
Execution failed for task ':connectivity_plus:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':connectivity_plus:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: C:\Users\dhili\AppData\Local\Android\sdk\platforms\android-34\core-for-system-modules.jar.
         > Error while executing process C:\Program Files\Android\Android Studio\jbr\bin\jlink.exe with arguments {--module-path C:\Users\dhili\.gradle\caches\transforms-3\72f109696607c2a2e011467aa233cdad\transformed\output\temp\jmod --add-modules java.base --output C:\Users\dhili\.gradle\caches\transforms-3\72f109696607c2a2e011467aa233cdad\transformed\output\jdkImage --disable-plugin system-modules}
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.4317], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.2)
[√] Connected device (4 available)
[√] Network resources
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project
