### ISSUE TITLE
[Compile]: 

### ISSUE THREAD

**Issue by fabiandumaguala** [fluttercommunity/plus_plugins#3357]
### Operating System

windows 11

### Plugin

connectivity_plus 

### Version

6.1.0

### Flutter SDK

3.24.4

### Compilation command

flutter run

### Dart Dependencies

```yaml
device_preview: ^1.2.0
  wave: ^0.2.2
  flutter_neumorphic_plus: ^3.4.0
  flutter_card_swiper: ^7.0.1
  flutter_carousel_widget: ^3.0.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  intl: ^0.19.0
  infinite_scroll_pagination: ^4.0.0
  flutter_slidable: ^3.1.1
  avatar_glow: ^3.0.1
  widget_zoom: ^0.0.4
  http: ^1.2.2
  odoo_rpc: ^0.5.8
  flutter_secure_storage: ^9.2.2
  flutter_cache_manager: ^3.4.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.0
  flutter_launcher_icons: ^0.14.1
```

### Compilation Error

```shell
Your project is configured with Android NDK 23.1.7779620, but the following plugin(s) depend on a different Android NDK version:
- connectivity_plus requires Android NDK 27.0.12077973
- flutter_secure_storage requires Android NDK 27.0.12077973
- path_provider_android requires Android NDK 27.0.12077973
- shared_preferences_android requires Android NDK 27.0.12077973
- sqflite_android requires Android NDK 27.0.12077973
Fix this issue by using the highest Android NDK version (they are backward compatible).
Add the following to C:\Users\Lenovo\Downloads\app\android\app\build.gradle:

    android {
        ndkVersion = "27.0.12077973"
        ...
    }
```

### Flutter Doctor

```shell
 flutter doctor -v
[√] Flutter (Channel stable, 3.24.4, on Microsoft Windows [Version 10.0.26100.2314], locale en-US)
    • Flutter version 3.24.4 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (3 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\Lenovo\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35327.3
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] VS Code (version 1.95.2)
    • VS Code at C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.100.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.26100.2314]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 130.0.6723.117
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 130.0.2849.80

[√] Network resources
    • All expected network resources are available.

• No issues found!
PS C:\Users\Lenovo\Downloads\canchafacil>
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project
