### ISSUE TITLE
[Compile]: Execution failed for task ':connectivity_plus:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by obed-king** [fluttercommunity/plus_plugins#3416]
### Operating System

MacOs Sequoia

### Plugin

connectivity_plus

### Version

6.1.1

### Flutter SDK

3.24.2

### Compilation command

flutter run

### Dart Dependencies

```yaml
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  shared_preferences: ^2.3.2
  flutter_screenutil: ^5.9.3
  supabase_flutter: ^2.6.0
  equatable: ^2.0.5
  connectivity_plus: ^6.1.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get: ^4.6.6
  get_it: ^7.7.0
  flutter_google_maps_webservices: ^1.1.1
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.0
  uuid: ^4.4.2
  http: ^1.2.2
  otp_text_field: ^1.1.3
  flutter_svg: ^2.0.10+1
  dropdown_button2: ^2.3.9
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.2.1
```

### Compilation Error

```shell
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':connectivity_plus:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':connectivity_plus:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /Users/obedkingjohnson/Library/Android/sdk/platforms/android-34/core-for-system-modules.jar.
         > Error while executing process /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/jlink with arguments {--module-path /Users/obedkingjohnson/.gradle/caches/transforms-3/d9e926982c2c139ff9125eb7b6be4144/transformed/output/temp/jmod --add-modules java.base --output /Users/obedkingjohnson/.gradle/caches/transforms-3/d9e926982c2c139ff9125eb7b6be4144/transformed/output/jdkImage --disable-plugin system-modules}

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 6s
Error: Gradle task assembleDebug failed with exit code 1
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.24.2, on macOS 15.1.1 24B91 darwin-arm64, locale en-CA)
    • Flutter version 3.24.2 on channel stable at /Users/obedkingjohnson/flutter/flutter_sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (4 months ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/obedkingjohnson/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/obedkingjohnson/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/obedkingjohnson/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.3.1)
    • IntelliJ at /Users/obedkingjohnson/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (4 available)
    • SM F926U1 (mobile)              • RFCR814HETB           • android-arm64  • Android 14 (API 34)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 131.0.6778.205

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project
