### ISSUE TITLE
[Compile]:warning: incompatible pointer types initializing 'NSNumber *' with an expression of type 'NSObject<NSCoding,NSCopying,NSSecureCoding> *

### ISSUE THREAD

**Issue by huanguan1978** [fluttercommunity/plus_plugins#3467]
### Operating System

macOS 12.7.6 21H1320 darwin-x64, locale en-HK

### Plugin

package_info_plus

### Version

8.2.0

### Flutter SDK

3.27.3

### Compilation command

1. cd ~/Documents/Projects/avatar/gai
2. flutter clean 
3. flutter pub get --no-example
4. flutter build macos --obfuscate --split-debug-info=build/macos/Build/Products/Release

### Dart Dependencies

```yaml
name: gai
description: "Generative AI Tools for Beginner"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  xor_dart: ^1.0.2
  shared_preferences: ^2.2.2
  talker: ^4.0.2
  talker_flutter: ^4.0.2
  talker_bloc_logger: ^4.0.2
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  http_interceptor: ^2.0.0-beta.8
  go_router: ^14.1.3
  device_info_plus: ^11.0.0
  package_info_plus: ^8.0.0
  equatable: ^2.0.5
  http: ^1.2.0
  mime: ^2.0.0

  flutter_localizations:
    sdk: flutter
  intl: any
  patching:
    path: ../patching
  afv:
    path: ../afv
  geminimodel:
    path: ../geminimodel

  check_app_version:
    path: ../check_app_version
  flutter_udid:
    path: ../flutter_udid
  freefont:
    path: ../freefont
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  path: ^1.9.0
  chat_bubbles: ^1.5.0
  jwt_decode: ^0.3.1
  flutter_markdown: ^0.7.1
  qr_flutter: ^4.1.0
  pointycastle: ^3.8.0
  cron: ^0.6.0
  json_schema: ^5.1.7
  file_selector: ^1.0.3
  http_parser: ^4.0.2
  mailer: ^6.1.0
  url_launcher: ^6.2.6
  memory_cache: ^1.2.0
  markdown: ^7.2.2
  another_flutter_splash_screen: ^1.2.0
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  responsive_framework: ^1.4.0
  network_to_file_image: ^7.0.0
  flutter_typeahead: ^5.2.0
  share_plus: ^10.0.2
  basic_logger: ^0.1.1

  basic_http_interceptor: ^0.0.4
  talker_http_logger: ^0.1.0-dev.11
  rfc_6901: ^0.2.0
  flutter_dotenv: ^5.1.0
  get_it: ^8.0.0
  logging: ^1.2.0
  loading_overlay: ^0.4.2
  flutter_material_design_icons: ^1.1.7447
  window_manager: ^0.4.3
#  flutter_udid: ^4.0.0
  internet_connection_checker_plus: ^2.2.0
#  check_app_version: ^2.0.0

# dependency_overrides:
#   mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

#  package_rename: any
#  flutter_launcher_icons: any
 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true # Add this line
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - .env  
    - assets/gai_icon_rounded_512x512.png
    - assets/gai_icon_rounded_512x512.svg    
    - assets/gai_icon_square_512x512.svg
    - assets/gai_icon_square_512x512.png
    - assets/gai_appimage.desktop
    - assets/gai_appstream_metainfo.xml
    - assets/gai_flatpak.desktop
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Droid Sans Fallback
      fonts:
        - asset: packages/freefont/fonts/DroidSansFallback.ttf
          weight: 400
          style: normal
    # - family: Mengshen HanSerif
    #   fonts:
    #     - asset: packages/freefont/fonts/Mengshen-HanSerif.ttf
    #       weight: 400
    #       style: normal
    # - family: Mengshen Handwritten
    #   fonts:
    #     - asset: packages/freefont/fonts/Mengshen-Handwritten.ttf
    #       weight: 400
    #       style: normal
    # - family: Noto Sans SC
    #   fonts:
    #     - asset: packages/freefont/fonts/NotoSansSC-Thin.ttf
    #       weight: 100
    #     - asset: packages/freefont/fonts/NotoSansSC-ExtraLight.ttf
    #       weight: 200
    #     - asset: packages/freefont/fonts/NotoSansSC-Light.ttf
    #       weight: 300
    #     - asset: packages/freefont/fonts/NotoSansSC-Regular.ttf
    #       weight: 400
    #     - asset: packages/freefont/fonts/NotoSansSC-Medium.ttf
    #       weight: 500
    #     - asset: packages/freefont/fonts/NotoSansSC-SemiBold.ttf
    #       weight: 600
    #     - asset: packages/freefont/fonts/NotoSansSC-Bold.ttf
    #       weight: 700
    #     - asset: packages/freefont/fonts/NotoSansSC-ExtraBold.ttf
    #       weight: 800
    #     - asset: packages/freefont/fonts/NotoSansSC-Black.ttf
    #       weight: 900
    # - family: Noto Serif SC
    #   fonts:
    #     - asset: packages/freefont/fonts/NotoSerifSC-ExtraLight.otf
    #       weight: 200
    #     - asset: packages/freefont/fonts/NotoSerifSC-Light.otf
    #       weight: 300
    #     - asset: packages/freefont/fonts/NotoSerifSC-Regular.otf
    #       weight: 400
    #     - asset: packages/freefont/fonts/NotoSerifSC-Medium.otf
    #       weight: 500
    #     - asset: packages/freefont/fonts/NotoSerifSC-SemiBold.otf
    #       weight: 600
    #     - asset: packages/freefont/fonts/NotoSerifSC-Bold.otf
    #       weight: 700
    #     - asset: packages/freefont/fonts/NotoSerifSC-Black.otf
    #       weight: 900
    # - family: Noto Serif TC
    #   fonts:
    #     - asset: packages/freefont/fonts/NotoSerifTC-ExtraLight.otf
    #       weight: 200
    #     - asset: packages/freefont/fonts/NotoSerifTC-Light.otf
    #       weight: 300
    #     - asset: packages/freefont/fonts/NotoSerifTC-Regular.otf
    #       weight: 400
    #     - asset: packages/freefont/fonts/NotoSerifTC-Medium.otf
    #       weight: 500
    #     - asset: packages/freefont/fonts/NotoSerifTC-SemiBold.otf
    #       weight: 600
    #     - asset: packages/freefont/fonts/NotoSerifTC-Bold.otf
    #       weight: 700
    #     - asset: packages/freefont/fonts/NotoSerifTC-Black.otf
    #       weight: 900
    # - family: Roboto
    #   fonts:
    #     - asset: packages/freefont/fonts/Roboto-Thin.ttf
    #       weight: 100
    #     - asset: packages/freefont/fonts/Roboto-ThinItalic.ttf
    #       style: italic
    #       weight: 100
    #     - asset: packages/freefont/fonts/Roboto-Light.ttf
    #       weight: 300
    #     - asset: packages/freefont/fonts/Roboto-LightItalic.ttf
    #       style: italic
    #       weight: 300
    #     - asset: packages/freefont/fonts/Roboto-Regular.ttf
    #       weight: 400
    #     - asset: packages/freefont/fonts/Roboto-Italic.ttf
    #       style: italic
    #       weight: 400
    #     - asset: packages/freefont/fonts/Roboto-Medium.ttf
    #       weight: 500
    #     - asset: packages/freefont/fonts/Roboto-MediumItalic.ttf
    #       style: italic
    #       weight: 500
    #     - asset: packages/freefont/fonts/Roboto-Bold.ttf
    #       weight: 700
    #     - asset: packages/freefont/fonts/Roboto-BoldItalic.ttf
    #       style: italic
    #       weight: 700
    #     - asset: packages/freefont/fonts/Roboto-Black.ttf
    #       weight: 900
    #     - asset: packages/freefont/fonts/Roboto-BlackItalic.ttf
    #       style: italic
    #       weight: 900

package_rename_config:
  # macos:
  #   app_name: Gai
  #   package_name: com.iche2.gai.macos
  #   copyright_notice: © 2025 Heshan Aisipai E-commerce Co., Ltd. All rights reserved.
  # ios:
  #   app_name: Gai
  #   bundle_name: Gai
  #  package_name: com.iche2.gai.ios

  # web:
  #   app_name: Gai
  #   description: A Generative-AI Tools For Beginners.

  linux:
    app_name: Gai
    package_name: com.iche2.gai.linux
    exe_name: gai

  # android:
  #  app_name: Gai
  #  package_name: com.iche2.gai.android
    # override_old_package: com.example.example
    # lang: kotlin

  # windows:
  #   app_name: Gai
  #   organization: Heshan Aisipai E-commerce Co., Ltd.
  #   copyright_notice: © 2025 Heshan Aisipai E-commerce Co., Ltd. All rights reserved.
  #   exe_name: gai-win64


flutter_launcher_icons:
  image_path: "assets/gai_icon_square_512x512.png"
  android: "launcher_icon"
  min_sdk_android: 26
  image_path_android : "assets/gai_icon_square_512x512.png"  
  ios: false
  image_path_ios : "assets/gai_icon_rounded_512x512.png"
  remove_alpha_ios: true
  macos:
    generate: false
    image_path: "assets/gai_icon_rounded_512x512.png"
  windows:
    generate: false
    image_path: "assets/gai_icon_square_512x512.png"
    icon_size: 48 # min:48, max:256, default: 48
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
```

### Native dependencies

```text
# macos/podfile

platform :osx, '10.15'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.15'
    end    
  end
end
```

### Compilation Error

```shell
kaguya@kaguya-MacBookPro gai % flutter build macos --obfuscate --split-debug-info=build/macos/Build/Products/Release

Running pod install...                                           1,804ms
/Users/kaguya/.pub-cache/hosted/pub.dev/package_info_plus-8.2.0/macos/package_info_plus/Sources/package_info_plus/FPPPackageInfoPlusPlugin.m:22:15: warning: incompatible pointer types initializing 'NSNumber *' with an expression of type 'NSObject<NSCoding,NSCopying,NSSecureCoding> *' [-Wincompatible-pointer-types]
    NSNumber *installTimeMillis = installDate ? @((long long)([installDate timeIntervalSince1970] * 1000)) : [NSNull null];
              ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
/Users/kaguya/.pub-cache/hosted/pub.dev/package_info_plus-8.2.0/macos/package_info_plus/Sources/package_info_plus/FPPPackageInfoPlusPlugin.m:22:15: warning: incompatible pointer types initializing 'NSNumber *' with an expression of type 'NSObject<NSCoding,NSCopying,NSSecureCoding> *' [-Wincompatible-pointer-types]
    NSNumber *installTimeMillis = installDate ? @((long long)([installDate timeIntervalSince1970] * 1000)) : [NSNull null];
              ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
Building macOS application...                                           
✓ Built build/macos/Build/Products/Release/Gai.app (61.2MB)
```

### Flutter Doctor

```shell
kaguya@kaguya-MacBookPro gai % flutter doctor -v
[✓] Flutter (Channel stable, 3.27.3, on macOS 12.7.6 21H1320 darwin-x64, locale en-HK)
    • Flutter version 3.27.3 on channel stable at /Users/kaguya/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c519ee916e (2 weeks ago), 2025-01-21 10:32:23 -0800
    • Engine revision e672b006cb
    • Dart version 3.6.1
    • DevTools version 2.40.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Users/kaguya/development/Xcode.app/Contents/Developer
    • Build 14C18
    ! Flutter recommends a minimum Xcode version of 15.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[✓] VS Code (version 1.97.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.104.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,127.0.0.1,localhost,*.local,timestamp.apple.com,sequoia.apple.com,seed-sequoia.siri.apple.com,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.7.6 21H1320 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 133.0.6943.53

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
kaguya@kaguya-MacBookPro gai %
```

### Checklist before submitting a bug

- [x] I searched issues in this repository and couldn't find such bug/problem
- [x] I Google'd a solution and I couldn't find it
- [x] I searched on StackOverflow for a solution and I couldn't find it
- [x] I read the README.md file of the plugin
- [x] I'm using the latest version of the plugin
- [x] All dependencies are up to date with `flutter pub upgrade`
- [x] I did a `flutter clean`
- [x] I tried running the example project
