### ISSUE TITLE
[RunTime]: Not able to run project due to device_info_plus: ^11.2.0

### ISSUE THREAD

**Issue by RupBarad** [fluttercommunity/plus_plugins#3546]
### Operating System

Apple M1 pro

### Plugin

device_info_plus: ^11.2.0

### Version

tried with 11.3.3, 11.2.0

### Flutter SDK

Flutter 3.29.2 • channel stable • https://github.com/flutter/flutter.git

### Compilation command

cmd: fluttr build apk
error on android

./../../.pub-cache/hosted/pub.dev/device_info_plus-11.3.3/lib/src/device_info_plus_windows.dart:138:23: Error: The getter 'ComputerNameDnsFullyQualified' isn't defined for the class 'DeviceInfoPlusWindowsPlugin'.
 - 'DeviceInfoPlusWindowsPlugin' is from 'package:device_info_plus/src/device_info_plus_windows.dart' ('../../../.pub-cache/hosted/pub.dev/device_info_plus-11.3.3/lib/src/device_info_plus_windows.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ComputerNameDnsFullyQualified'.
    GetComputerNameEx(ComputerNameDnsFullyQualified, nullptr, nSize);
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/device_info_plus-11.3.3/lib/src/device_info_plus_windows.dart:144:29: Error: The getter 'ComputerNameDnsFullyQualified' isn't defined for the class 'DeviceInfoPlusWindowsPlugin'.
 - 'DeviceInfoPlusWindowsPlugin' is from 'package:device_info_plus/src/device_info_plus_windows.dart' ('../../../.pub-cache/hosted/pub.dev/device_info_plus-11.3.3/lib/src/device_info_plus_windows.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ComputerNameDnsFullyQualified'.
          GetComputerNameEx(ComputerNameDnsFullyQualified, lpBuffer, nSize);
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/win32_registry-2.1.0/lib/src/registry_key.dart:323:25: Error: The getter 'WAIT_OBJECT_0' isn't defined for the class 'RegistryKey'.
 - 'RegistryKey' is from 'package:win32_registry/src/registry_key.dart' ('../../../.pub-cache/hosted/pub.dev/win32_registry-2.1.0/lib/src/registry_key.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WAIT_OBJECT_0'.
          if (result == WAIT_OBJECT_0) {
                        ^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/win32_registry-2.1.0/lib/src/registry_key.dart:327:32: Error: The getter 'WAIT_TIMEOUT' isn't defined for the class 'RegistryKey'.
 - 'RegistryKey' is from 'package:win32_registry/src/registry_key.dart' ('../../../.pub-cache/hosted/pub.dev/win32_registry-2.1.0/lib/src/registry_key.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WAIT_TIMEOUT'.
          } else if (result == WAIT_TIMEOUT) {
                               ^^^^^^^^^^^^
Target kernel_snapshot_program failed: Exception

cmd: flutter clean, flutter pub get, cd ios, pod install, cd .., flutter run
error on iOS:

Error (Xcode): ../../../.pub-cache/hosted/pub.dev/device_info_plus-11.3.3/lib/src/device_info_plus_windows.dart:138:23: Error:
The getter 'ComputerNameDnsFullyQualified' isn't defined for the class 'DeviceInfoPlusWindowsPlugin'.

Could not build the application for the simulator.
Error launching application on iPhone 16 Pro.

### Dart Dependencies

```yaml
version: 1.1.7+19

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  app_tracking_transparency: ^2.0.5
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  cloud_firestore: ^5.4.4
  collection: 1.19.1
  connectivity_plus: ^6.1.0
  csslib: 0.17.3
  device_info_plus: ^11.2.0
  dropdown_button2: 2.3.9
  easy_debounce: 2.0.1
  equatable: 2.0.5
  event_bus: ^2.0.1
  file_picker: 8.1.2
  firebase_analytics: 11.3.5
  firebase_analytics_platform_interface: 4.2.7
  firebase_analytics_web: 0.5.10+4
  firebase_auth: 5.3.3
  firebase_auth_platform_interface: 7.4.9
  firebase_auth_web: 5.13.4
  firebase_core: 3.8.0
  firebase_core_platform_interface: 5.3.0
  firebase_core_web: 2.18.1
  firebase_crashlytics: 4.1.5
  firebase_crashlytics_platform_interface: 3.6.46
  firebase_database: ^11.1.4
  firebase_messaging: ^15.0.0
  firebase_performance: 0.10.0+10
  firebase_performance_platform_interface: 0.1.4+46
  firebase_performance_web: 0.1.7+4
  firebase_remote_config: 5.1.5
  firebase_remote_config_platform_interface: 1.4.46
  firebase_remote_config_web: 1.7.4
  firebase_storage: 12.3.2
  firebase_storage_platform_interface: 5.1.33
  firebase_storage_web: 3.10.5
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.4.1
  flutter_keyboard_visibility: 6.0.0
  flutter_keyboard_visibility_linux: 1.0.0
  flutter_keyboard_visibility_macos: 1.0.0
  flutter_keyboard_visibility_platform_interface: 2.0.0
  flutter_keyboard_visibility_web: 2.0.0
  flutter_keyboard_visibility_windows: 1.0.0
  flutter_local_notifications: ^17.2.4
  flutter_native_splash: 2.4.1
  flutter_plugin_android_lifecycle: 2.0.20
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.0
  flutterflow_colorpicker: 
    git:
      url: https://github.com/FlutterFlow/flutterflow_colorpicker.git
      ref: v0.0.1+1
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  google_mobile_ads: 5.1.0
  google_sign_in: 6.2.1
  google_sign_in_android: 6.1.30
  google_sign_in_ios: 5.7.7
  google_sign_in_platform_interface: 2.4.5
  google_sign_in_web: 0.12.4+2
  html: 0.15.4
  html_to_pdf: ^0.8.1
  http: 1.2.2
  image_picker: 1.1.2
  image_picker_android: 0.8.12+13
  image_picker_for_web: 3.0.5
  image_picker_ios: 0.8.12
  image_picker_linux: 0.2.1+1
  image_picker_macos: 0.2.1+1
  image_picker_platform_interface: 2.10.0
  image_picker_windows: 0.2.1+1
  in_app_review: ^2.0.10
  internet_connection_checker_plus: ^2.5.2
  intl: 0.19.0
  json_path: 0.7.2
  mime_type: 1.0.0
  open_file: ^3.5.10
  package_info_plus: ^8.1.1
  page_transition: 2.1.0
  path_provider: 2.1.4
  path_provider_android: 2.2.10
  path_provider_foundation: 2.4.0
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  pdf: ^3.8.4
  permission_handler: ^11.3.1
  plugin_platform_interface: 2.1.8
  pointer_interceptor: 0.10.1+2
  pointer_interceptor_ios: 0.10.1
  pointer_interceptor_platform_interface: 0.10.0+1
  pointer_interceptor_web: 0.10.2+1
  printing: ^5.13.4
  provider: 6.1.2
  rxdart: 0.27.7
  share_plus: 10.0.2
  share_plus_platform_interface: 5.0.0
  shared_preferences: 2.3.2
  shared_preferences_android: 2.3.2
  shared_preferences_foundation: 2.5.2
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: 2.4.2
  shared_preferences_windows: 2.4.1
  sign_in_with_apple: 6.1.2
  sign_in_with_apple_platform_interface: 1.1.0
  sign_in_with_apple_web: 2.1.0
  simple_gradient_text: 1.2.3
  sqflite: 2.3.3+1
  sqflite_common: 2.5.4+3
  stop_watch_timer: 3.0.2
  timeago: 3.6.1
  timezone: ^0.9.0
  universal_io: 2.2.2
  url_launcher: 6.3.0
  url_launcher_android: 6.3.10
  url_launcher_ios: 6.3.1
  url_launcher_linux: 3.2.0
  url_launcher_macos: 3.2.1
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: 2.3.3
  url_launcher_windows: 3.1.2
  uuid: ^4.0.0
  video_player: 2.9.2
  video_player_android: 2.7.13
  video_player_avfoundation: 2.6.2
  video_player_platform_interface: 6.2.3
  video_player_web: 2.3.2
  webview_flutter: 4.9.0
  webview_flutter_android: 3.16.7
  webview_flutter_platform_interface: 2.10.0
  webview_flutter_wkwebview: 3.15.0
  webviewx_plus: 0.5.0
  xml: 6.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.2
  pointer_interceptor: 0.10.1+2
  pointer_interceptor_ios: 0.10.1
  pointer_interceptor_platform_interface: 0.10.0+1
  pointer_interceptor_web: 0.10.2+1
  uuid: ^4.0.0
  win32: 5.5.1

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  image: 4.2.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'
  adaptive_icon_background: '#f8e5bf'
  adaptive_icon_foreground: 'assets/images/adaptive_foreground_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
```

### Native dependencies

```text

```

### Compilation Error

```shell
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/device_info_plus-11.3.3/lib/src/device_info_plus_windows.dart:138:23: Error:
The getter 'ComputerNameDnsFullyQualified' isn't defined for the class 'DeviceInfoPlusWindowsPlugin'.


Could not build the application for the simulator.
Error launching application on iPhone 16 Pro.
```

### Flutter Doctor

```shell
flutter doctor -v
[✓] Flutter (Channel stable, 3.29.2, on macOS 15.3.2 24D81 darwin-arm64, locale en-US) [2.3s]
    • Flutter version 3.29.2 on channel stable at /Users/rupb/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c236373904 (5 weeks ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [1,965ms]
    • Android SDK at /Users/rupb/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • ANDROID_HOME = /Users/rupb/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment Corretto-17.0.14.7.1 (build 17.0.14+7-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [1,724ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [10ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [10ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-13047016-b750.29)

[✓] VS Code (version 1.98.2) [9ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.108.0

[✓] Connected device (4 available) [11.9s]    
    • iPhone 16 Pro (mobile)          • E1A6C315-BEE6-4D8C-9588-976647354AAD • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-18-3 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.3.2 24D81 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.3.2 24D81 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 135.0.7049.96
    ! Error: Browsing on the local area network for iPad (2). Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPad Air 3rd Generation. Ensure the device is unlocked and attached with a
      cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [427ms]
    • All expected network resources are available.

• No issues found!
rupb@Rups-MacBook-Pro ToDoApp %
```

### Checklist before submitting a bug

- [x] I searched issues in this repository and couldn't find such bug/problem
- [x] I Google'd a solution and I couldn't find it
- [x] I searched on StackOverflow for a solution and I couldn't find it
- [x] I read the README.md file of the plugin
- [x] I'm using the latest version of the plugin
- [x] All dependencies are up to date with `flutter pub upgrade`
- [x] I did a `flutter clean`
- [x] I tried running the example project
