### ISSUE TITLE
[package_info_plus] Incorrect prerelease version returned on iOS

### ISSUE THREAD

**Issue by rubenvereecken** [fluttercommunity/plus_plugins#389]
This bug occurs only on iOS. Our prerelease versions look like this:

```
1.0.56-beta.4+1324
```

On Android, all is well:
```dart
// Android
> print((await PackageInfo.fromPlatform()).version)
1.0.56-beta.4
```

On iOS however, the prerelease bit `-beta` gets dropped, resulting in a semver-invalid version string. 
```dart
// iOS
> print((await PackageInfo.fromPlatform()).version)
1.0.56.4
```

We have some migration logic that runs depending on version which now doesn't run on iOS because it throws.

In case this bit of our pubspec.lock is useful:
```
  package_info_plus:
    dependency: "direct main"
    description:
      name: package_info_plus
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  package_info_plus_macos:
    dependency: transitive
    description:
      name: package_info_plus_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.1"
```
