### ISSUE TITLE
[Bug]: [Share_Plus] - 'Save to File' converting images to PNG and losing filename

### ISSUE THREAD

**Issue by zambetpentru** [fluttercommunity/plus_plugins#914]
### Platform

ios / ipad 15

### Plugin

share_plus

### Version

4.0.8

### Flutter SDK

3.0.1

### Steps to reproduce

Greetings @Coronon, when using your sample repo below and Share_Plus 4.0.8 when I try to use Save to File with an image it will convert it to PNG, but when sharing a pdf file it saves it correctly. This happens on iPhone and iPad and simulators for them.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/81489824/174430532-9b921f07-b801-44ce-a175-ea340f1d34b4.png">

### Code Sample

```dart
The Repo in https://github.com/Coronon/share_plus_example
```

### Logs

```shell
Too long
```
```


### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-GB)
    • Flutter version 3.0.1 at /users/omega/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (4 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/omega/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 1CB4A48C-9038-46C2-9196-285DEE0B7C31 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5
      (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by Coronon** [comment]
Hi there, first of all thank you for contacting me directly ;) I don’t really understand the problem, do you mean the file name or an internal conversion of the file type?

**Comment by zambetpentru** [comment]
Greetings! Yes, both the filename gets replaced with 'png image' and the filetype is also converted from your sample jpgs to pngs.

**Comment by Coronon** [comment]
I was able to reproduce the bug and think that I found a proper fix. The PR is now open for review.

Please do me a favor and check if my [example project](https://github.com/Coronon/share_plus_example) fixes this issue and if you are able to save your images with their proper file names by including the following in your `pubspec.yaml`:

```yaml
dependency_overrides:
  share_plus:
    git:
      url: https://github.com/Coronon/plus_plugins
      ref: 0e3e2bb978ab876016e8a7ea8760759a7ff8f998
      path: packages/share_plus/share_plus
  share_plus_linux:
    git:
      url: https://github.com/Coronon/plus_plugins
      ref: 0e3e2bb978ab876016e8a7ea8760759a7ff8f998
      path: packages/share_plus/share_plus_linux
  share_plus_macos:
    git:
      url: https://github.com/Coronon/plus_plugins
      ref: 0e3e2bb978ab876016e8a7ea8760759a7ff8f998
      path: packages/share_plus/share_plus_macos
  share_plus_platform_interface:
    git:
      url: https://github.com/Coronon/plus_plugins
      ref: 0e3e2bb978ab876016e8a7ea8760759a7ff8f998
      path: packages/share_plus/share_plus_platform_interface
  share_plus_web:
    git:
      url: https://github.com/Coronon/plus_plugins
      ref: 0e3e2bb978ab876016e8a7ea8760759a7ff8f998
      path: packages/share_plus/share_plus_web
  share_plus_windows:
    git:
      url: https://github.com/Coronon/plus_plugins
      ref: 0e3e2bb978ab876016e8a7ea8760759a7ff8f998
      path: packages/share_plus/share_plus_windows
```
